var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                            o o                                 ",
   "                                                                                ",
   "                                           xxxxxx                               ",
   "                                                                                ",
   "                                        y                                       ",
   "             o                                                                  ",
   "                                     xxxxx                                      ",
   "                                                                  o             ",
   "           xxxxx                xxxxx                                           ",
   "                                                                xxxxx           ",
   "                         o                              o       xxxxx     o     ",
   "     @                                                          xxxxx           ",
   " xxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                    x x                         x   x                           ",
   "                    x x                         x   x                           ",
   "                    x x                         x   x                           ",
   "                    x x                         x   x                           ",
   "                    x x                         x   x                           ",
   "                    x x                         x   x                           "],

  ["                                                                             ",
   "                               o                                             ",
   "                                                                             ",
   "                             xxxxx                                           ",
   "                                                                             ",
   "                                                                             ",
   "                                            xxxx                             ",
   "                                   o                         o               ",
   "                                 ^                                   y       ",
   "                                 xxxxxx                                      ",
   "                                 x  v                      xxxxxxxxxxxxxxxxxx",
   "                                 x                  o         v             x",
   "                                 x                                          x",
   "                                 x                                          x",
   "                                 x                                        o x",
   "                                 x                     ^                    x",
   "     @                           x     xxxx   x  x  x  x  x  x  x    x  xxxxx",
   " ^xxxxxxx^                       x     x                                     ",
   "^xxxxxxxxx^                      xx    x                                     ",
   "xxxxxxxxxxx                      x     x                                     ",
   "xxxxxxxxxxx                      x     x                                     ",
   "xxxxxxxxxxx                      x     x                                     ",
   "xxxxxxxxxxx            ^         x     x                                     ",
   "xxxxxxxxxxx     xx     xx        x    xx                                     ",
   "xxxxxxxxxxx      x  o  x         x     x                                     ",
   "xxxxxxxxxxx      x     x         x     x                                     ",
   "xxxxxxxxxxx      x     xxxxxxxxxxx     x                                     ",
   "xxxxxxxxxxx      x                     x                                     ",
   "xxxxxxxxxxx      x        o            x                                     ",
   "xxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxxxx                                    "],

  ["                                                                                                              ",
   "                                                                                                              ",
   "          v     v        v      v       v         v           v      v         v         v               v    ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                         @           ",
   "                                        x                                                         x           ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                                                                    ",
   "                                       x x                                                                    ",
   "                                     xxx xx                                                                   ",
   "                                      x   x                                                                   ",
   "                                     Ox   xxxx                                                                ",
   "                                      x   x v                                                                 ",
   "                                  xxxxx   x    o                                                              ",
   "                                      x   x                                                                   ",
   "                                      x   x                                                                   ",
   "                                      x   xxxxxxxx                     o                                      ",
   "                                     xx   x                  xxxxx                                            ",
   "                                      x   x                                                                   ",
   "                                      x   x                           x                                       ",
   "                                      x o x                                                                   ",
   "      y                                   x                                      xxxx                         ",
   "                              o           x                                                                   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx^^^^^ xxx^^x                                                                   ",
   "                                                                                                              ",
   "                                                                                                             "],

  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "               o  o  o   o  oo    o  oo    o  ooooooo  oooooo  o                                              ",
   "               o  o  o   o  o o   o  o o   o  o        o    o  o                                              ",
   "               o  o  o   o  o  o  o  o  o  o  oooooo   oooooo  o                                              ",
   "               o  o  o   o  o   o o  o   o o  o        o  o                                                   ",
   "               ooooooo   o  o    oo  o    oo  ooooooo  o   o   o                                              ",
   "   @                                                                                                          ",
   "            s                                                                                                  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
